CREATE SCHEMA IF NOT EXISTS "NETWORK" AUTHORIZATION "DEFIDEMO";
CREATE SCHEMA IF NOT EXISTS "PROFILE" AUTHORIZATION "DEFIDEMO";
CREATE SCHEMA IF NOT EXISTS "TRANSACTIONS" AUTHORIZATION "DEFIDEMO";
--CREATE SCHEMA IF NOT EXISTS "POLYGON";
--CREATE SCHEMA IF NOT EXISTS "BINANCE";